/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as CuratorRouteImport } from './routes/curator'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BuddyRouteImport } from './routes/buddy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SphereSphereIdRouteImport } from './routes/sphere.$sphereId'
import { Route as MentorsMentorIdRouteImport } from './routes/mentors_.$mentorId'
import { Route as MaterialIdRouteImport } from './routes/material.$id'
import { Route as GroupsGroupIdRouteImport } from './routes/groups_.$groupId'
import { Route as EventsEventIdRouteImport } from './routes/events_.$eventId'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorRoute = CuratorRouteImport.update({
  id: '/curator',
  path: '/curator',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddyRoute = BuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SphereSphereIdRoute = SphereSphereIdRouteImport.update({
  id: '/sphere/$sphereId',
  path: '/sphere/$sphereId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsMentorIdRoute = MentorsMentorIdRouteImport.update({
  id: '/mentors_/$mentorId',
  path: '/mentors/$mentorId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups_/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buddy': typeof BuddyRoute
  '/community': typeof CommunityRoute
  '/curator': typeof CuratorRoute
  '/cycle': typeof CycleRoute
  '/edit-profile': typeof EditProfileRoute
  '/events': typeof EventsRoute
  '/groups': typeof GroupsRoute
  '/mentor': typeof MentorRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/topics': typeof TopicsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/material/$id': typeof MaterialIdRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/sphere/$sphereId': typeof SphereSphereIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buddy': typeof BuddyRoute
  '/community': typeof CommunityRoute
  '/curator': typeof CuratorRoute
  '/cycle': typeof CycleRoute
  '/edit-profile': typeof EditProfileRoute
  '/events': typeof EventsRoute
  '/groups': typeof GroupsRoute
  '/mentor': typeof MentorRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/topics': typeof TopicsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/material/$id': typeof MaterialIdRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/sphere/$sphereId': typeof SphereSphereIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buddy': typeof BuddyRoute
  '/community': typeof CommunityRoute
  '/curator': typeof CuratorRoute
  '/cycle': typeof CycleRoute
  '/edit-profile': typeof EditProfileRoute
  '/events': typeof EventsRoute
  '/groups': typeof GroupsRoute
  '/mentor': typeof MentorRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/topics': typeof TopicsRoute
  '/events_/$eventId': typeof EventsEventIdRoute
  '/groups_/$groupId': typeof GroupsGroupIdRoute
  '/material/$id': typeof MaterialIdRoute
  '/mentors_/$mentorId': typeof MentorsMentorIdRoute
  '/sphere/$sphereId': typeof SphereSphereIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buddy'
    | '/community'
    | '/curator'
    | '/cycle'
    | '/edit-profile'
    | '/events'
    | '/groups'
    | '/mentor'
    | '/mentors'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/topics'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/material/$id'
    | '/mentors/$mentorId'
    | '/sphere/$sphereId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/buddy'
    | '/community'
    | '/curator'
    | '/cycle'
    | '/edit-profile'
    | '/events'
    | '/groups'
    | '/mentor'
    | '/mentors'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/topics'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/material/$id'
    | '/mentors/$mentorId'
    | '/sphere/$sphereId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buddy'
    | '/community'
    | '/curator'
    | '/cycle'
    | '/edit-profile'
    | '/events'
    | '/groups'
    | '/mentor'
    | '/mentors'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/topics'
    | '/events_/$eventId'
    | '/groups_/$groupId'
    | '/material/$id'
    | '/mentors_/$mentorId'
    | '/sphere/$sphereId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuddyRoute: typeof BuddyRoute
  CommunityRoute: typeof CommunityRoute
  CuratorRoute: typeof CuratorRoute
  CycleRoute: typeof CycleRoute
  EditProfileRoute: typeof EditProfileRoute
  EventsRoute: typeof EventsRoute
  GroupsRoute: typeof GroupsRoute
  MentorRoute: typeof MentorRoute
  MentorsRoute: typeof MentorsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  TopicsRoute: typeof TopicsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  MaterialIdRoute: typeof MaterialIdRoute
  MentorsMentorIdRoute: typeof MentorsMentorIdRoute
  SphereSphereIdRoute: typeof SphereSphereIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator': {
      id: '/curator'
      path: '/curator'
      fullPath: '/curator'
      preLoaderRoute: typeof CuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy': {
      id: '/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof BuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sphere/$sphereId': {
      id: '/sphere/$sphereId'
      path: '/sphere/$sphereId'
      fullPath: '/sphere/$sphereId'
      preLoaderRoute: typeof SphereSphereIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors_/$mentorId': {
      id: '/mentors_/$mentorId'
      path: '/mentors/$mentorId'
      fullPath: '/mentors/$mentorId'
      preLoaderRoute: typeof MentorsMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups_/$groupId': {
      id: '/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId': {
      id: '/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuddyRoute: BuddyRoute,
  CommunityRoute: CommunityRoute,
  CuratorRoute: CuratorRoute,
  CycleRoute: CycleRoute,
  EditProfileRoute: EditProfileRoute,
  EventsRoute: EventsRoute,
  GroupsRoute: GroupsRoute,
  MentorRoute: MentorRoute,
  MentorsRoute: MentorsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  TopicsRoute: TopicsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  MaterialIdRoute: MaterialIdRoute,
  MentorsMentorIdRoute: MentorsMentorIdRoute,
  SphereSphereIdRoute: SphereSphereIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
